### ISSUE TITLE
Tailwind css 每次修改了之后，需要重新 build，样式才会生效？

### ISSUE THREAD

**Issue by linghuccc** [openbuildxyz/Web3-Frontend-Bootcamp#194]
我用 npm create vite@latest 创建了 project，然后按照 https://tailwindcss.com/docs/installation 的步骤， 手动安装了Tailwind CLI，但奇怪的是，每次我更改页面的格式，必须重新 run 一次 “npx tailwindcss -i ./src/input.css -o ./src/output.css --watch”，新的格式才会在页面显示出来，否则不会生效。
是我漏了哪个设置的步骤么？

project 地址：
https://github.com/linghuccc/openbuild-frontend/tree/main/task1-todolist

**Comment by majoson-chen** [comment]
就是这样的，tailwind 是需要编译的。类似问题请到 discussions 中提问

**Comment by linghuccc** [comment]
> 就是这样的，tailwind 是需要编译的。类似问题请到 discussions 中提问

我用 "npx create-next-app@latest" 生成的 Next JS project，都是修改了之后，直接显示的，不需要每次 run 一遍 build

**Comment by majoson-chen** [comment]
可能是其他工具进行了 watch-build，例如 webpack，或者 vite，因此给你造成了错觉
类似问题请到 discussions 中提问

**Comment by linghuccc** [comment]
> 可能是其他工具进行了 watch-build，例如 webpack，或者 vite，因此给你造成了错觉 类似问题请到 discussions 中提问

收到
